"""Slack AI app simulator — persona-driven stand-in for any marketplace AI app.

Config is driven by config/app_config.json (generated by the onboarding wizard
in CLAUDE.md). That file specifies display name, persona markdown path, model,
loading messages, and whether to detect Block Kit responses.

Listens via Socket Mode for DMs (message.im) and channel mentions (app_mention),
plus assistant_thread_started for the Slack "Agents & Assistants" sidebar UX.
Generates replies by subprocessing the `claude` CLI — no Anthropic SDK, no API
keys in this process.
"""
from __future__ import annotations

import argparse
import json
import logging
import random
import re
import sys
import time
import traceback
from collections import defaultdict
from pathlib import Path
from threading import Event, Lock, Thread
from typing import Any

from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
from slack_sdk.socket_mode import SocketModeClient
from slack_sdk.socket_mode.request import SocketModeRequest
from slack_sdk.socket_mode.response import SocketModeResponse

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config import agent_bot_client, audit_log, load_app_config, load_tokens  # noqa: E402
from agent.claude_subprocess import EMPTY_USAGE, one_shot, stream_reply  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
MAX_TURNS = 20
STREAM_FLUSH_MS = 400
STREAM_CHUNK_CHARS = 30
LOADING_INTERVAL_MIN_S = 1.5
LOADING_INTERVAL_MAX_S = 3.0
LOADING_FLOOR_MIN_S = 7.0
LOADING_FLOOR_MAX_S = 10.0
BLOCKKIT_DETECT_CHARS = 14
BLOCKKIT_FENCE_RE = re.compile(r"^\s*```blockkit\s*\n(.*?)\n```\s*$", re.DOTALL)

log = logging.getLogger("simulator")


class Simulator:
    def __init__(self, *, stream: bool = True):
        cfg = load_app_config()
        self.cfg = cfg
        self.display_name: str = cfg["display_name"]
        self.app_name: str = cfg.get("app_name", self.display_name)
        self.simulates: str = cfg.get("simulates", "(unspecified)")
        self.model: str = cfg.get("model", "sonnet")
        self.loading_messages: list[str] = cfg.get("loading_messages") or [
            f"is thinking...",
            f"is drafting a reply...",
            f"is considering...",
            f"is composing...",
        ]
        self.blockkit_enabled: bool = bool(cfg.get("blockkit_enabled", False))
        self.stream = stream

        persona_rel = cfg.get("persona_path")
        if not persona_rel:
            raise SystemExit("app_config.json missing 'persona_path'. Re-run onboarding.")
        persona_path = ROOT / persona_rel
        if not persona_path.exists():
            raise SystemExit(f"Persona file not found: {persona_path}. Re-run onboarding.")
        self.system_prompt = persona_path.read_text().strip()
        self.persona_path = persona_path

        tokens = load_tokens()
        agent_tokens = tokens.get("agent", {})
        missing = [k for k in ("bot_token", "bot_user_id", "app_token") if not agent_tokens.get(k)]
        if missing:
            raise SystemExit(
                f"tokens.json missing agent fields: {missing}. See SETUP.md steps 6-7."
            )
        if not tokens.get("team_id"):
            raise SystemExit("tokens.json missing 'team_id'. See SETUP.md step 8.")

        self.bot_user_id: str = agent_tokens["bot_user_id"]
        self.team_id: str = tokens["team_id"]
        self.web: WebClient = agent_bot_client()
        self.app_token: str = agent_tokens["app_token"]

        self.history: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
        self.history_lock = Lock()
        self.titled: set[tuple[str, str]] = set()
        self.thread_context: dict[tuple[str, str], str] = {}

        self.socket = SocketModeClient(app_token=self.app_token, web_client=self.web)
        self.socket.socket_mode_request_listeners.append(self._on_request)

    # ---- entry point ------------------------------------------------------

    def run(self) -> None:
        self._dump_scopes()
        log.info("Connecting to Slack via Socket Mode...")
        self.socket.connect()
        audit_log(
            f":sparkles: {self.display_name} online — simulates=`{self.simulates}` "
            f"model=`{self.model}` user_id=`{self.bot_user_id}`"
        )
        log.info("%s is online. Ctrl+C to stop. DO NOT close this Terminal window.", self.display_name)
        Event().wait()  # block forever

    def _dump_scopes(self) -> None:
        required = (
            "assistant:write",
            "chat:write",
            "im:history",
            "channels:history",
            "app_mentions:read",
        )
        try:
            resp = self.web.auth_test()
            scopes_header = resp.headers.get("x-oauth-scopes") or ""
            scopes = [s.strip() for s in scopes_header.split(",") if s.strip()]
        except SlackApiError as e:
            log.error("auth.test failed; cannot list scopes: %s", e.response.get("error"))
            audit_log(f":warning: {self.display_name} startup auth.test failed: `{e.response.get('error')}`")
            return
        log.info("bot scopes (%d): %s", len(scopes), ", ".join(scopes) or "(none)")
        missing = [s for s in required if s not in scopes]
        for s in required:
            log.info("  %s: %s", s, "OK" if s in scopes else "MISSING")
        present_summary = " ".join(
            f"{s}={'✓' if s in scopes else '✗'}" for s in required
        )
        if missing:
            audit_log(
                f":warning: {self.display_name} scopes — MISSING: `{', '.join(missing)}`. "
                f"Status indicator + auto-title need `assistant:write`. "
                f"All scopes: {present_summary}"
            )
        else:
            audit_log(f":white_check_mark: {self.display_name} scopes OK — {present_summary}")

    # ---- socket mode dispatch --------------------------------------------

    def _on_request(self, client: SocketModeClient, req: SocketModeRequest) -> None:
        client.send_socket_mode_response(SocketModeResponse(envelope_id=req.envelope_id))
        if req.type != "events_api":
            return

        event = req.payload.get("event", {})
        etype = event.get("type")

        try:
            if etype == "message" and event.get("channel_type") == "im":
                self._handle_message(event, is_dm=True)
            elif etype == "app_mention":
                self._handle_message(event, is_dm=False)
            elif etype == "assistant_thread_started":
                self._handle_thread_started(req.payload)
            elif etype == "assistant_thread_context_changed":
                self._handle_context_changed(req.payload)
        except Exception:
            log.exception("Error handling event %s", etype)
            audit_log(f":warning: {self.display_name} error on `{etype}`:\n```{traceback.format_exc()[:1500]}```")

    # ---- handlers ---------------------------------------------------------

    def _handle_thread_started(self, payload: dict[str, Any]) -> None:
        thread = payload.get("event", {}).get("assistant_thread", {})
        channel = thread.get("channel_id")
        thread_ts = thread.get("thread_ts")
        if not channel or not thread_ts:
            return
        ctx_channel = thread.get("context", {}).get("channel_id")
        if ctx_channel:
            self.thread_context[(channel, thread_ts)] = ctx_channel
        self._post(channel, thread_ts, "Hi — what can I help you with?")

    def _handle_context_changed(self, payload: dict[str, Any]) -> None:
        thread = payload.get("event", {}).get("assistant_thread", {})
        channel = thread.get("channel_id")
        thread_ts = thread.get("thread_ts")
        ctx_channel = thread.get("context", {}).get("channel_id")
        if not channel or not thread_ts:
            return
        if ctx_channel:
            self.thread_context[(channel, thread_ts)] = ctx_channel
            log.info("context changed: thread=%s now viewing channel=%s", thread_ts, ctx_channel)
        else:
            self.thread_context.pop((channel, thread_ts), None)

    def _handle_message(self, event: dict[str, Any], *, is_dm: bool) -> None:
        if event.get("user") == self.bot_user_id:
            return
        if event.get("bot_id") or event.get("subtype") in {"bot_message", "message_changed", "message_deleted"}:
            return

        user_id = event.get("user")
        channel = event.get("channel")
        text = event.get("text", "").strip()
        if not (user_id and channel and text):
            return

        thread_ts = event.get("thread_ts") or event.get("ts")
        key = (channel, thread_ts)

        if not is_dm:
            text = text.replace(f"<@{self.bot_user_id}>", "").strip()
            if not text:
                text = "(you were mentioned with no other text)"

        with self.history_lock:
            is_first_turn = len(self.history[key]) == 0
            self.history[key].append({"role": "user", "content": text})
            messages = list(self.history[key][-MAX_TURNS:])

        ctx_channel = self.thread_context.get(key)
        system_prompt = self.system_prompt
        if ctx_channel:
            system_prompt += f"\n\n---\n\nThe user is currently viewing channel <#{ctx_channel}>."

        if is_dm and is_first_turn and key not in self.titled:
            self.titled.add(key)
            Thread(
                target=self._set_title_from_question,
                args=(channel, thread_ts, text),
                daemon=True,
            ).start()

        loading_stop = Event()
        self._set_status(channel, thread_ts, self.loading_messages[0])
        Thread(
            target=self._loading_loop,
            args=(channel, thread_ts, loading_stop),
            daemon=True,
        ).start()

        t0 = time.time()
        try:
            reply, usage = self._stream_reply(
                channel, thread_ts, user_id, system_prompt, messages, loading_stop
            )
        except Exception as e:
            loading_stop.set()
            log.exception("claude subprocess failed")
            audit_log(f":x: {self.display_name} Claude error: `{type(e).__name__}` — {str(e)[:300]}")
            self._post(channel, thread_ts, "Sorry, I hit an error reaching my brain. Try again?")
            self._set_status(channel, thread_ts, "")
            return
        elapsed = time.time() - t0

        with self.history_lock:
            self.history[key].append({"role": "assistant", "content": reply})

        self._set_status(channel, thread_ts, "")

        audit_log(
            f":speech_balloon: {self.display_name}→<@{user_id}> in <#{channel}> "
            f"simulates=`{self.simulates}` {elapsed:.1f}s"
        )

    def _loading_loop(self, channel: str, thread_ts: str, stop: Event) -> None:
        i = 0
        while not stop.wait(random.uniform(LOADING_INTERVAL_MIN_S, LOADING_INTERVAL_MAX_S)):
            i = (i + 1) % len(self.loading_messages)
            self._set_status(channel, thread_ts, self.loading_messages[i])

    def _set_title_from_question(self, channel: str, thread_ts: str, question: str) -> None:
        try:
            title = one_shot(
                model=self.model,
                system_prompt=(
                    "You generate short Slack thread titles. Given the user's first message, "
                    "respond with a 4-7 word title that summarizes the topic. "
                    "No quotes, no trailing punctuation, no leading verbs like 'asking about'."
                ),
                user_text=question[:500],
                timeout=30,
            )
            title = title.strip("\"'.").strip()
            if not title:
                return
            self.web.assistant_threads_setTitle(
                channel_id=channel, thread_ts=thread_ts, title=title[:100]
            )
        except SlackApiError as e:
            err = e.response.get("error")
            log.error("assistant.threads.setTitle failed: %s", err)
            audit_log(
                f":warning: {self.display_name} `assistant.threads.setTitle` rejected → `{err}` "
                f"(check `assistant:write` scope)"
            )
        except Exception as e:
            log.error("setTitle failed: %s", e)
            audit_log(f":warning: {self.display_name} setTitle failed: `{type(e).__name__}: {e}`")

    # ---- side effects -----------------------------------------------------

    def _post(self, channel: str, thread_ts: str, text: str) -> str | None:
        try:
            resp = self.web.chat_postMessage(
                channel=channel,
                thread_ts=thread_ts,
                text=text,
                username=self.display_name,
            )
            return resp.get("ts")
        except SlackApiError as e:
            log.error("chat.postMessage failed: %s", e.response.get("error"))
            return None

    def _set_status(self, channel: str, thread_ts: str, status: str) -> None:
        try:
            self.web.assistant_threads_setStatus(
                channel_id=channel,
                thread_ts=thread_ts,
                status=status,
            )
        except SlackApiError as e:
            err = e.response.get("error")
            log.error("assistant.threads.setStatus failed: %s", err)
            audit_log(
                f":warning: {self.display_name} `assistant.threads.setStatus` rejected → `{err}` "
                f"(check `assistant:write` scope + 'Agents & AI Apps' feature toggle)"
            )

    # ---- Claude call ------------------------------------------------------

    def _stream_reply(
        self,
        channel: str,
        thread_ts: str,
        user_id: str,
        system_prompt: str,
        messages: list[dict[str, str]],
        loading_stop: Event,
    ) -> tuple[str, dict[str, Any]]:
        t_start = time.monotonic()
        floor_s = random.uniform(LOADING_FLOOR_MIN_S, LOADING_FLOOR_MAX_S)

        if not self.stream:
            return self._reply_no_stream(
                channel, thread_ts, system_prompt, messages, t_start, floor_s, loading_stop
            )

        buf = ""
        ts: str | None = None
        last_flush = time.monotonic()
        started_streaming = False
        detect_phase = self.blockkit_enabled
        is_blockkit = False
        final_text = ""
        error_text: str | None = None

        def _flush() -> None:
            nonlocal buf, last_flush
            if not buf or ts is None:
                return
            try:
                self.web.chat_appendStream(
                    channel=channel,
                    ts=ts,
                    markdown_text=buf,
                )
            except SlackApiError as e:
                err = e.response.get("error")
                log.error("chat.appendStream failed: %s", err)
                audit_log(
                    f":warning: {self.display_name} `chat.appendStream` rejected → `{err}` "
                    f"(stream stuck on placeholder)"
                )
            buf = ""
            last_flush = time.monotonic()

        def _start_stream() -> bool:
            nonlocal ts
            try:
                start_resp = self.web.chat_startStream(
                    channel=channel,
                    thread_ts=thread_ts,
                    recipient_team_id=self.team_id,
                    recipient_user_id=user_id,
                    username=self.display_name,
                )
                ts = start_resp.get("ts")
                return True
            except SlackApiError as e:
                err = e.response.get("error")
                log.error("chat.startStream failed (%s)", err)
                audit_log(
                    f":warning: {self.display_name} `chat.startStream` rejected → `{err}`. "
                    f"Falling back to plain `chat.postMessage` (no streaming)."
                )
                return False

        try:
            stream_iter = stream_reply(
                model=self.model,
                system_prompt=system_prompt,
                messages=messages,
            )
            for event_type, payload in stream_iter:
                if event_type == "error":
                    error_text = payload
                    continue
                if event_type == "final":
                    final_text = payload
                    break
                if event_type != "delta":
                    continue

                buf += payload

                if detect_phase:
                    if len(buf) < BLOCKKIT_DETECT_CHARS:
                        continue
                    detect_phase = False
                    is_blockkit = buf.lstrip().startswith("```blockkit")
                    if is_blockkit:
                        continue

                if is_blockkit:
                    continue

                if not started_streaming:
                    remaining = floor_s - (time.monotonic() - t_start)
                    if remaining > 0:
                        time.sleep(remaining)
                    if not _start_stream():
                        loading_stop.set()
                        self._set_status(channel, thread_ts, "")
                        for ev_type2, payload2 in stream_iter:
                            if ev_type2 == "delta":
                                buf += payload2
                            elif ev_type2 == "final":
                                final_text = payload2
                                break
                            elif ev_type2 == "error":
                                error_text = payload2
                        text = (final_text or buf).strip() or "(no response)"
                        self._post(channel, thread_ts, text)
                        return text, EMPTY_USAGE
                    started_streaming = True
                    loading_stop.set()
                    self._set_status(channel, thread_ts, "")
                elif (time.monotonic() - last_flush) * 1000 >= STREAM_FLUSH_MS:
                    _flush()
        finally:
            loading_stop.set()

        if error_text and not final_text:
            raise RuntimeError(f"claude CLI error: {error_text[:500]}")

        full_text = final_text.strip() or buf.strip() or "(no response)"

        # Late-arriving Block Kit detection: when the CLI only emits a terminal
        # `result` event (no incremental deltas), detect_phase never flipped.
        # Re-inspect the full text now.
        if detect_phase and self.blockkit_enabled:
            is_blockkit = full_text.lstrip().startswith("```blockkit")

        # Fallback path: no deltas ever arrived AND we never opened a stream.
        # Post the full reply as a single chat.postMessage after the loading
        # floor so the UX still feels right (loading spinner → reply bubble).
        if not started_streaming and not is_blockkit:
            remaining = floor_s - (time.monotonic() - t_start)
            if remaining > 0:
                time.sleep(remaining)
            loading_stop.set()
            self._set_status(channel, thread_ts, "")
            self._post(channel, thread_ts, full_text)
            return full_text, EMPTY_USAGE

        # Block Kit path: parse the fence, wait out the floor, post as blocks.
        if is_blockkit:
            blocks = None
            m = BLOCKKIT_FENCE_RE.match(full_text)
            if m:
                try:
                    parsed = json.loads(m.group(1))
                    blocks = parsed if isinstance(parsed, list) else parsed.get("blocks")
                except (ValueError, AttributeError) as e:
                    log.warning("blockkit fence found but JSON invalid: %s", e)
            remaining = floor_s - (time.monotonic() - t_start)
            if remaining > 0:
                time.sleep(remaining)
            loading_stop.set()
            self._set_status(channel, thread_ts, "")
            if blocks:
                try:
                    self.web.chat_postMessage(
                        channel=channel,
                        thread_ts=thread_ts,
                        blocks=blocks,
                        text="(Block Kit card)",
                        username=self.display_name,
                    )
                except SlackApiError as e:
                    err = e.response.get("error")
                    log.error("chat.postMessage (blocks) failed: %s", err)
                    audit_log(f":warning: {self.display_name} blocks post rejected → `{err}`")
                    self._post(channel, thread_ts, full_text)
            else:
                audit_log(
                    f":warning: {self.display_name} Block Kit fence unparseable. "
                    f"Raw start: ```{full_text[:200]}```"
                )
                self._post(channel, thread_ts, "Sorry, I botched the card formatting. Try again?")
            return full_text, EMPTY_USAGE

        # Normal streaming path: finish replaying the buffered reply paced.
        pending = buf
        buf = ""
        final_chunk = ""
        while pending:
            chunk, pending = pending[:STREAM_CHUNK_CHARS], pending[STREAM_CHUNK_CHARS:]
            if not pending:
                final_chunk = chunk
                break
            try:
                self.web.chat_appendStream(
                    channel=channel, ts=ts, markdown_text=chunk
                )
            except SlackApiError as e:
                err = e.response.get("error")
                log.error("chat.appendStream failed: %s", err)
                break
            time.sleep(STREAM_FLUSH_MS / 1000)

        try:
            stop_kwargs: dict[str, Any] = {"channel": channel, "ts": ts}
            if final_chunk:
                stop_kwargs["markdown_text"] = final_chunk
            self.web.chat_stopStream(**stop_kwargs)
        except SlackApiError as e:
            err = e.response.get("error")
            log.error("chat.stopStream failed: %s", err)
            audit_log(
                f":warning: {self.display_name} `chat.stopStream` rejected → `{err}` "
                f"(final flush failed; placeholder may remain)"
            )

        return full_text, EMPTY_USAGE

    def _reply_no_stream(
        self,
        channel: str,
        thread_ts: str,
        system_prompt: str,
        messages: list[dict[str, str]],
        t_start: float,
        floor_s: float,
        loading_stop: Event,
    ) -> tuple[str, dict[str, Any]]:
        parts: list[str] = []
        for ev_type, payload in stream_reply(
            model=self.model,
            system_prompt=system_prompt,
            messages=messages,
        ):
            if ev_type == "delta":
                parts.append(payload)
            elif ev_type == "final":
                full = payload.strip()
                if full:
                    parts = [full]
                break
            elif ev_type == "error":
                raise RuntimeError(f"claude CLI error: {payload[:500]}")

        text = "".join(parts).strip() or "(no response)"

        remaining = floor_s - (time.monotonic() - t_start)
        if remaining > 0:
            time.sleep(remaining)
        loading_stop.set()
        self._set_status(channel, thread_ts, "")

        blocks = None
        if self.blockkit_enabled:
            m = BLOCKKIT_FENCE_RE.match(text)
            if m:
                try:
                    parsed = json.loads(m.group(1))
                    blocks = parsed if isinstance(parsed, list) else parsed.get("blocks")
                except (ValueError, AttributeError):
                    pass
        if blocks:
            try:
                self.web.chat_postMessage(
                    channel=channel,
                    thread_ts=thread_ts,
                    blocks=blocks,
                    text="(Block Kit card)",
                    username=self.display_name,
                )
            except SlackApiError:
                self._post(channel, thread_ts, text)
        else:
            self._post(channel, thread_ts, text)
        return text, EMPTY_USAGE


def main() -> int:
    parser = argparse.ArgumentParser(description="Slack AI app simulator")
    parser.add_argument(
        "--no-stream",
        action="store_true",
        help="Disable native text streaming (chat.startStream); use single chat.postMessage instead.",
    )
    parser.add_argument("--debug", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.debug else logging.INFO,
        format="%(asctime)s %(levelname)-7s %(name)s: %(message)s",
    )

    Simulator(stream=not args.no_stream).run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
