"""Slack AI app simulator — persona-driven stand-in for any marketplace AI app.

Config is driven by config/app_config.json (generated by the onboarding wizard
in CLAUDE.md). That file specifies display name, persona markdown path, model,
loading messages, and whether to detect Block Kit responses.

Listens via Socket Mode for DMs (message.im) and channel mentions (app_mention),
plus assistant_thread_started for the Slack "Agents & Assistants" sidebar UX.
Generates replies by subprocessing the `claude` CLI — no Anthropic SDK, no API
keys in this process.
"""
from __future__ import annotations

import argparse
import json
import logging
import random
import re
import sys
import time
import traceback
from collections import defaultdict
from pathlib import Path
from threading import Event, Lock, Thread
from typing import Any

from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
from slack_sdk.socket_mode import SocketModeClient
from slack_sdk.socket_mode.request import SocketModeRequest
from slack_sdk.socket_mode.response import SocketModeResponse

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config import agent_bot_client, audit_log, load_app_config, load_tokens  # noqa: E402
from agent.claude_subprocess import EMPTY_USAGE, one_shot, stream_reply  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
MAX_TURNS = 20
STREAM_FLUSH_MS = 400
STREAM_CHUNK_CHARS = 30
LOADING_INTERVAL_MIN_S = 1.5
LOADING_INTERVAL_MAX_S = 3.0
LOADING_FLOOR_MIN_S = 7.0
LOADING_FLOOR_MAX_S = 10.0

# Block Kit extraction + decision logic.
#
# The model is asked to emit its entire response as a single ```blockkit fence
# wrapping a JSON array. In practice it sometimes adds a trailing sentence,
# runs out of tokens mid-JSON, or produces valid JSON that violates Slack's
# schema. These helpers classify failures so the runtime can fall back
# gracefully and the audit log tells you *which* bucket broke (parse_error /
# schema_error / trailing_prose / truncated). See qa.py --self-test for the
# fixture set that covers each path.
BLOCKKIT_FENCE_RE = re.compile(r"^\s*```blockkit\s*\n(.*?)\n```\s*$", re.DOTALL)
_BLOCKKIT_LOOSE_RE = re.compile(r"```blockkit\s*\n(.*?)\n```", re.DOTALL)
_ALLOWED_BLOCK_TYPES = {"header", "divider", "section", "context", "actions", "image"}
_ALLOWED_ELEMENT_TYPES = {"mrkdwn", "plain_text", "image"}

# When deciding "is this reply a Block Kit card?" during streaming: don't
# commit to plain-text streaming too early — the model occasionally emits a
# short sentence before the fence and we'd stream the lead-in + the raw JSON
# if we commit to text before the fence arrives. Buffer until we have
# enough to decide OR we're close to the loading-floor end.
BLOCKKIT_DECISION_MIN_CHARS = 14
BLOCKKIT_DECISION_MARGIN_S = 0.2

log = logging.getLogger("simulator")


def _balanced_array_slice(s: str) -> str | None:
    """Return the substring from the first '[' to its matching ']', respecting
    quoted strings and escapes. Used as a last-ditch recovery when a closing
    ``` fence is missing (truncated output)."""
    start = s.find("[")
    if start == -1:
        return None
    depth = 0
    in_str = False
    escape = False
    for i in range(start, len(s)):
        c = s[i]
        if in_str:
            if escape:
                escape = False
            elif c == "\\":
                escape = True
            elif c == '"':
                in_str = False
        else:
            if c == '"':
                in_str = True
            elif c == "[":
                depth += 1
            elif c == "]":
                depth -= 1
                if depth == 0:
                    return s[start : i + 1]
    return None


def _extract_blockkit_json(text: str) -> tuple[list | None, str]:
    """Try progressively looser strategies to pull a blocks list out of text.

    Returns (blocks_or_None, tier) where tier is one of:
      - "strict"        — exact ```blockkit…``` fence, response is only the fence
      - "trailing_prose"— fence present but extra text before/after
      - "truncated"     — no closing fence; bracket-walked the JSON array
      - "parse_error"   — extraction found something but JSON parse failed
      - "no_fence"      — no ```blockkit marker at all
    """
    m = BLOCKKIT_FENCE_RE.match(text)
    if m:
        try:
            parsed = json.loads(m.group(1))
            blocks = parsed if isinstance(parsed, list) else parsed.get("blocks")
            if isinstance(blocks, list):
                return blocks, "strict"
        except (ValueError, AttributeError):
            return None, "parse_error"

    m = _BLOCKKIT_LOOSE_RE.search(text)
    if m:
        try:
            parsed = json.loads(m.group(1))
            blocks = parsed if isinstance(parsed, list) else parsed.get("blocks")
            if isinstance(blocks, list):
                return blocks, "trailing_prose"
        except (ValueError, AttributeError):
            return None, "parse_error"

    if "```blockkit" in text:
        after = text.split("```blockkit", 1)[1]
        arr = _balanced_array_slice(after)
        if arr:
            try:
                parsed = json.loads(arr)
                if isinstance(parsed, list):
                    return parsed, "truncated"
            except ValueError:
                return None, "parse_error"
        return None, "parse_error"

    return None, "no_fence"


def _validate_blocks(blocks: list) -> list[str]:
    """Cheap subset-check of Slack's Block Kit constraints. Returns a list of
    human-readable violations; empty list means "looks postable."""
    violations: list[str] = []
    if not isinstance(blocks, list):
        return ["top-level is not a list"]
    if len(blocks) > 50:
        violations.append(f"too many blocks: {len(blocks)} (max 50)")
    for i, b in enumerate(blocks):
        if not isinstance(b, dict):
            violations.append(f"block[{i}] is not an object")
            continue
        t = b.get("type")
        if t not in _ALLOWED_BLOCK_TYPES:
            violations.append(f"block[{i}].type={t!r} not in allowed set")
            continue
        if t == "header":
            txt = (b.get("text") or {})
            if txt.get("type") != "plain_text":
                violations.append(f"block[{i}] header.text.type must be plain_text")
            if len(txt.get("text", "")) > 150:
                violations.append(f"block[{i}] header.text >150 chars")
        elif t == "section":
            txt = b.get("text")
            if not isinstance(txt, dict):
                violations.append(f"block[{i}] section missing text object")
            else:
                if txt.get("type") not in {"mrkdwn", "plain_text"}:
                    violations.append(f"block[{i}] section.text.type invalid")
                if len(txt.get("text", "")) > 3000:
                    violations.append(f"block[{i}] section.text >3000 chars")
        elif t == "context":
            els = b.get("elements")
            if not isinstance(els, list):
                violations.append(f"block[{i}] context.elements missing")
            else:
                if len(els) > 10:
                    violations.append(f"block[{i}] context.elements >10")
                for j, el in enumerate(els):
                    if not isinstance(el, dict) or el.get("type") not in _ALLOWED_ELEMENT_TYPES:
                        violations.append(f"block[{i}].elements[{j}].type invalid")
    return violations


def _blockkit_decision(buf: str, elapsed_s: float, floor_s: float) -> str:
    """Decide what to do with a streaming buffer during the detect phase.

    Returns one of:
      - "buffer"   — keep accumulating; no decision yet.
      - "blockkit" — a ```blockkit fence has appeared; switch to blockkit path.
      - "text"     — no fence likely; commit to plain-text streaming.

    Why not just check the prefix: the model sometimes pre-faces the card
    with a short sentence ("Here are the top priorities:"). If we commit
    to plain-text streaming before the fence appears, the later fence gets
    streamed as raw JSON in a code block and the user sees garbage.
    """
    if "```blockkit" in buf:
        return "blockkit"
    if len(buf) < BLOCKKIT_DECISION_MIN_CHARS:
        return "buffer"
    if elapsed_s >= max(0.0, floor_s - BLOCKKIT_DECISION_MARGIN_S):
        return "text"
    return "buffer"


_NAME_BAD_CHARS = re.compile(r"[`*_~|<>\\\n\r\t]")


def _sanitize_user_name(name: str) -> str:
    """Strip Slack mrkdwn-control chars and newlines from a user-supplied
    display name before splicing it into the system prompt. Slack lets users
    pick any display name they want, including things like '*\\n\\nNew rules:'
    that would act as prompt injection. Cap length so a giant pasted name
    can't dominate the system prompt either."""
    cleaned = _NAME_BAD_CHARS.sub(" ", name).strip()
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned[:80]


def _has_blockkit_candidate(text: str) -> bool:
    """Return True when a completed reply should go through the Block Kit path.

    Streaming detection searches for a ```blockkit fence anywhere in the buffer.
    Keep final-result detection aligned with that behavior so terminal-only CLI
    results do not leak raw fenced JSON just because the model added a preface.
    """
    _, tier = _extract_blockkit_json(text)
    return tier != "no_fence"


class Simulator:
    def __init__(self, *, stream: bool = True):
        cfg = load_app_config()
        self.cfg = cfg
        self.display_name: str = cfg["display_name"]
        self.app_name: str = cfg.get("app_name", self.display_name)
        self.simulates: str = cfg.get("simulates", "(unspecified)")
        # Default to claude-sonnet-4-6 — the model the QA harness is
        # validated against and what most SEs have configured for Claude
        # Code. Override via app_config.json "model" field.
        self.model: str = cfg.get("model", "claude-sonnet-4-6")
        self.loading_messages: list[str] = cfg.get("loading_messages") or [
            f"is thinking...",
            f"is drafting a reply...",
            f"is considering...",
            f"is composing...",
        ]
        self.blockkit_enabled: bool = bool(cfg.get("blockkit_enabled", False))
        self.stream = stream

        persona_rel = cfg.get("persona_path")
        if not persona_rel:
            raise SystemExit("app_config.json missing 'persona_path'. Re-run onboarding.")
        persona_path = ROOT / persona_rel
        if not persona_path.exists():
            raise SystemExit(f"Persona file not found: {persona_path}. Re-run onboarding.")
        self.system_prompt = persona_path.read_text().strip()
        self.persona_path = persona_path

        tokens = load_tokens()
        agent_tokens = tokens.get("agent", {})
        missing = [k for k in ("bot_token", "bot_user_id", "app_token") if not agent_tokens.get(k)]
        if missing:
            raise SystemExit(
                f"tokens.json missing agent fields: {missing}. See SETUP.md steps 6-7."
            )
        if not tokens.get("team_id"):
            raise SystemExit("tokens.json missing 'team_id'. See SETUP.md step 8.")

        self.bot_user_id: str = agent_tokens["bot_user_id"]
        self.team_id: str = tokens["team_id"]
        self.web: WebClient = agent_bot_client()
        self.app_token: str = agent_tokens["app_token"]

        self.history: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
        self.history_lock = Lock()
        self.titled: set[tuple[str, str]] = set()
        self.thread_context: dict[tuple[str, str], str] = {}
        # Cache of Slack user display names, so the bot can be told who it's
        # talking to and avoid the "who are you?" failure mode on "my tasks"
        # style questions. None means lookup failed — still cached so we
        # don't hammer users.info on every message.
        self.user_names: dict[str, str | None] = {}
        self.user_names_lock = Lock()

        self.socket = SocketModeClient(app_token=self.app_token, web_client=self.web)
        self.socket.socket_mode_request_listeners.append(self._on_request)

    # ---- entry point ------------------------------------------------------

    def run(self) -> None:
        self._dump_scopes()
        log.info("Connecting to Slack via Socket Mode...")
        self.socket.connect()
        audit_log(
            f":sparkles: {self.display_name} online — simulates=`{self.simulates}` "
            f"model=`{self.model}` user_id=`{self.bot_user_id}`"
        )
        log.info("%s is online. Ctrl+C to stop. DO NOT close this Terminal window.", self.display_name)
        Event().wait()  # block forever

    def _dump_scopes(self) -> None:
        required = (
            "assistant:write",
            "chat:write",
            "im:history",
            "channels:history",
            "app_mentions:read",
            "users:read",  # needed for _resolve_user_name (identity injection)
        )
        try:
            resp = self.web.auth_test()
            scopes_header = resp.headers.get("x-oauth-scopes") or ""
            scopes = [s.strip() for s in scopes_header.split(",") if s.strip()]
        except SlackApiError as e:
            log.error("auth.test failed; cannot list scopes: %s", e.response.get("error"))
            audit_log(f":warning: {self.display_name} startup auth.test failed: `{e.response.get('error')}`")
            return
        log.info("bot scopes (%d): %s", len(scopes), ", ".join(scopes) or "(none)")
        missing = [s for s in required if s not in scopes]
        for s in required:
            log.info("  %s: %s", s, "OK" if s in scopes else "MISSING")
        present_summary = " ".join(
            f"{s}={'✓' if s in scopes else '✗'}" for s in required
        )
        if missing:
            audit_log(
                f":warning: {self.display_name} scopes — MISSING: `{', '.join(missing)}`. "
                f"Status indicator + auto-title need `assistant:write`. "
                f"All scopes: {present_summary}"
            )
        else:
            audit_log(f":white_check_mark: {self.display_name} scopes OK — {present_summary}")

    # ---- socket mode dispatch --------------------------------------------

    def _on_request(self, client: SocketModeClient, req: SocketModeRequest) -> None:
        client.send_socket_mode_response(SocketModeResponse(envelope_id=req.envelope_id))
        if req.type != "events_api":
            return

        event = req.payload.get("event", {})
        etype = event.get("type")

        try:
            if etype == "message" and event.get("channel_type") == "im":
                self._handle_message(event, is_dm=True)
            elif etype == "app_mention":
                self._handle_message(event, is_dm=False)
            elif etype == "assistant_thread_started":
                self._handle_thread_started(req.payload)
            elif etype == "assistant_thread_context_changed":
                self._handle_context_changed(req.payload)
        except Exception:
            log.exception("Error handling event %s", etype)
            audit_log(f":warning: {self.display_name} error on `{etype}`:\n```{traceback.format_exc()[:1500]}```")

    # ---- handlers ---------------------------------------------------------

    def _handle_thread_started(self, payload: dict[str, Any]) -> None:
        thread = payload.get("event", {}).get("assistant_thread", {})
        channel = thread.get("channel_id")
        thread_ts = thread.get("thread_ts")
        if not channel or not thread_ts:
            return
        ctx_channel = thread.get("context", {}).get("channel_id")
        if ctx_channel:
            self.thread_context[(channel, thread_ts)] = ctx_channel
        self._post(channel, thread_ts, "Hi — what can I help you with?")

    def _handle_context_changed(self, payload: dict[str, Any]) -> None:
        thread = payload.get("event", {}).get("assistant_thread", {})
        channel = thread.get("channel_id")
        thread_ts = thread.get("thread_ts")
        ctx_channel = thread.get("context", {}).get("channel_id")
        if not channel or not thread_ts:
            return
        if ctx_channel:
            self.thread_context[(channel, thread_ts)] = ctx_channel
            log.info("context changed: thread=%s now viewing channel=%s", thread_ts, ctx_channel)
        else:
            self.thread_context.pop((channel, thread_ts), None)

    def _handle_message(self, event: dict[str, Any], *, is_dm: bool) -> None:
        if event.get("user") == self.bot_user_id:
            return
        if event.get("bot_id") or event.get("subtype") in {"bot_message", "message_changed", "message_deleted"}:
            return

        user_id = event.get("user")
        channel = event.get("channel")
        text = event.get("text", "").strip()
        if not (user_id and channel and text):
            return

        thread_ts = event.get("thread_ts") or event.get("ts")
        key = (channel, thread_ts)

        if not is_dm:
            text = text.replace(f"<@{self.bot_user_id}>", "").strip()
            if not text:
                text = "(you were mentioned with no other text)"

        with self.history_lock:
            is_first_turn = len(self.history[key]) == 0
            self.history[key].append({"role": "user", "content": text})
            messages = list(self.history[key][-MAX_TURNS:])

        ctx_channel = self.thread_context.get(key)
        system_prompt = self.system_prompt
        if ctx_channel:
            system_prompt += f"\n\n---\n\nThe user is currently viewing channel <#{ctx_channel}>."
        # Identity injection — tell the model who it's talking to so it
        # doesn't ask for a name on "my tasks / my priorities" style
        # questions. Cached per user_id; None means we couldn't resolve,
        # and we skip the injection rather than inject garbage.
        user_name = self._resolve_user_name(user_id)
        if user_name:
            system_prompt += (
                f"\n\nThe user you are speaking with is *{user_name}*. "
                f"When they say 'my', 'me', or 'I', they are referring to themselves — "
                f"resolve it against the names in your persona data and answer accordingly. "
                f"Never ask who they are; you already know."
            )

        if is_dm and is_first_turn and key not in self.titled:
            self.titled.add(key)
            Thread(
                target=self._set_title_from_question,
                args=(channel, thread_ts, text),
                daemon=True,
            ).start()

        loading_stop = Event()
        self._set_status(channel, thread_ts, self.loading_messages[0])
        Thread(
            target=self._loading_loop,
            args=(channel, thread_ts, loading_stop),
            daemon=True,
        ).start()

        t0 = time.time()
        try:
            reply, usage = self._stream_reply(
                channel, thread_ts, user_id, system_prompt, messages, loading_stop
            )
        except Exception as e:
            loading_stop.set()
            log.exception("claude subprocess failed")
            audit_log(f":x: {self.display_name} Claude error: `{type(e).__name__}` — {str(e)[:300]}")
            self._post(channel, thread_ts, "Sorry, I hit an error reaching my brain. Try again?")
            self._set_status(channel, thread_ts, "")
            return
        elapsed = time.time() - t0

        with self.history_lock:
            self.history[key].append({"role": "assistant", "content": reply})

        self._set_status(channel, thread_ts, "")

        audit_log(
            f":speech_balloon: {self.display_name}→<@{user_id}> in <#{channel}> "
            f"simulates=`{self.simulates}` {elapsed:.1f}s"
        )

    def _loading_loop(self, channel: str, thread_ts: str, stop: Event) -> None:
        i = 0
        while not stop.wait(random.uniform(LOADING_INTERVAL_MIN_S, LOADING_INTERVAL_MAX_S)):
            i = (i + 1) % len(self.loading_messages)
            self._set_status(channel, thread_ts, self.loading_messages[i])

    def _set_title_from_question(self, channel: str, thread_ts: str, question: str) -> None:
        try:
            title = one_shot(
                model=self.model,
                system_prompt=(
                    "You generate short Slack thread titles. Given the user's first message, "
                    "respond with a 4-7 word title that summarizes the topic. "
                    "No quotes, no trailing punctuation, no leading verbs like 'asking about'."
                ),
                user_text=question[:500],
                timeout=30,
            )
            title = title.strip("\"'.").strip()
            if not title:
                return
            self.web.assistant_threads_setTitle(
                channel_id=channel, thread_ts=thread_ts, title=title[:100]
            )
        except SlackApiError as e:
            err = e.response.get("error")
            log.error("assistant.threads.setTitle failed: %s", err)
            audit_log(
                f":warning: {self.display_name} `assistant.threads.setTitle` rejected → `{err}` "
                f"(check `assistant:write` scope)"
            )
        except Exception as e:
            log.error("setTitle failed: %s", e)
            audit_log(f":warning: {self.display_name} setTitle failed: `{type(e).__name__}: {e}`")

    # ---- side effects -----------------------------------------------------

    def _resolve_user_name(self, user_id: str) -> str | None:
        """Return a Slack user's display name, cached per user_id. Prefers
        `profile.display_name` (what they chose to show), falls back to
        `profile.real_name` (their HR name), then `user.real_name`. Returns
        None on any failure — callers must treat missing names as 'no
        identity info available' rather than an error."""
        with self.user_names_lock:
            if user_id in self.user_names:
                return self.user_names[user_id]
        try:
            resp = self.web.users_info(user=user_id)
        except SlackApiError as e:
            err = e.response.get("error")
            log.warning("users.info failed for %s: %s", user_id, err)
            with self.user_names_lock:
                self.user_names[user_id] = None
            return None
        user = resp.get("user") or {}
        profile = user.get("profile") or {}
        name = (
            profile.get("display_name")
            or profile.get("real_name")
            or user.get("real_name")
            or None
        )
        if name:
            name = _sanitize_user_name(name) or None
        with self.user_names_lock:
            self.user_names[user_id] = name
        return name

    def _replay_buffered_text(self, channel: str, ts: str | None, text: str) -> None:
        """Replay a fully-buffered reply into Slack as paced chunks, mirroring
        the live-streaming cadence (STREAM_CHUNK_CHARS / STREAM_FLUSH_MS).
        The last chunk rides on chat.stopStream so the placeholder closes
        cleanly. Both the short-reply path (model finished fast, no stream
        opened mid-generation) and the long-reply path call this."""
        pending = text
        final_chunk = ""
        while pending:
            chunk, pending = pending[:STREAM_CHUNK_CHARS], pending[STREAM_CHUNK_CHARS:]
            if not pending:
                final_chunk = chunk
                break
            try:
                self.web.chat_appendStream(
                    channel=channel, ts=ts, markdown_text=chunk
                )
            except SlackApiError as e:
                err = e.response.get("error")
                hints = e.response.get("response_metadata", {}).get("messages") or []
                log.error("chat.appendStream failed: %s (%s)", err, hints)
                audit_log(
                    f":warning: {self.display_name} `chat.appendStream` rejected → `{err}` "
                    f"ts=`{ts}` chunk_len={len(chunk)} hints={hints}"
                )
                break
            time.sleep(STREAM_FLUSH_MS / 1000)

        if ts is None:
            audit_log(
                f":warning: {self.display_name} `chat.stopStream` skipped: `ts` was None "
                f"(startStream likely failed upstream; reply len={len(text)})"
            )
            return
        try:
            stop_kwargs: dict[str, Any] = {"channel": channel, "ts": ts}
            if final_chunk:
                stop_kwargs["markdown_text"] = final_chunk
            self.web.chat_stopStream(**stop_kwargs)
        except SlackApiError as e:
            err = e.response.get("error")
            hints = e.response.get("response_metadata", {}).get("messages") or []
            log.error("chat.stopStream failed: %s (%s)", err, hints)
            audit_log(
                f":warning: {self.display_name} `chat.stopStream` rejected → `{err}` "
                f"ts=`{ts}` final_chunk_len={len(final_chunk)} "
                f"reply_len={len(text)} hints={hints} "
                f"(final flush failed; placeholder may remain)"
            )

    def _finalize_dropped_stream(self, channel: str, ts: str | None, buf: str) -> None:
        """Close a Slack streaming message that was interrupted mid-reply
        (claude CLI subprocess died, network blip, etc.). Flushes any buffered
        text, then calls chat.stopStream with a short appended note so the
        user sees something instead of a half-frozen placeholder. Never raises."""
        if not ts:
            return
        tail = "\n\n_(connection dropped — please ask again)_"
        try:
            if buf:
                self.web.chat_appendStream(channel=channel, ts=ts, markdown_text=buf)
        except SlackApiError as e:
            err = e.response.get("error")
            hints = e.response.get("response_metadata", {}).get("messages") or []
            log.error("drop-finalize appendStream failed: %s (%s)", err, hints)
        try:
            self.web.chat_stopStream(
                channel=channel, ts=ts, markdown_text=tail
            )
        except SlackApiError as e:
            err = e.response.get("error")
            hints = e.response.get("response_metadata", {}).get("messages") or []
            log.error("drop-finalize stopStream failed: %s (%s)", err, hints)

    def _post(self, channel: str, thread_ts: str, text: str) -> str | None:
        try:
            resp = self.web.chat_postMessage(
                channel=channel,
                thread_ts=thread_ts,
                text=text,
                username=self.display_name,
            )
            return resp.get("ts")
        except SlackApiError as e:
            log.error("chat.postMessage failed: %s", e.response.get("error"))
            return None

    def _set_status(self, channel: str, thread_ts: str, status: str) -> None:
        try:
            self.web.assistant_threads_setStatus(
                channel_id=channel,
                thread_ts=thread_ts,
                status=status,
            )
        except SlackApiError as e:
            err = e.response.get("error")
            log.error("assistant.threads.setStatus failed: %s", err)
            audit_log(
                f":warning: {self.display_name} `assistant.threads.setStatus` rejected → `{err}` "
                f"(check `assistant:write` scope + 'Agents & AI Apps' feature toggle)"
            )

    # ---- Claude call ------------------------------------------------------

    def _stream_reply(
        self,
        channel: str,
        thread_ts: str,
        user_id: str,
        system_prompt: str,
        messages: list[dict[str, str]],
        loading_stop: Event,
    ) -> tuple[str, dict[str, Any]]:
        t_start = time.monotonic()
        floor_s = random.uniform(LOADING_FLOOR_MIN_S, LOADING_FLOOR_MAX_S)

        if not self.stream:
            return self._reply_no_stream(
                channel, thread_ts, system_prompt, messages, t_start, floor_s, loading_stop
            )

        buf = ""
        ts: str | None = None
        last_flush = time.monotonic()
        started_streaming = False
        detect_phase = self.blockkit_enabled
        is_blockkit = False
        final_text = ""
        error_text: str | None = None

        def _flush() -> None:
            nonlocal buf, last_flush
            if not buf or ts is None:
                return
            try:
                self.web.chat_appendStream(
                    channel=channel,
                    ts=ts,
                    markdown_text=buf,
                )
            except SlackApiError as e:
                err = e.response.get("error")
                log.error("chat.appendStream failed: %s", err)
                audit_log(
                    f":warning: {self.display_name} `chat.appendStream` rejected → `{err}` "
                    f"(stream stuck on placeholder)"
                )
            buf = ""
            last_flush = time.monotonic()

        def _start_stream() -> bool:
            """Open the Slack streaming placeholder. Returns False (with a
            fallback-to-postMessage audit note) on SlackApiError OR when the
            response comes back without a usable `ts`. The missing-ts branch
            protects us from downstream appendStream/stopStream calls that
            would fail with invalid_arguments."""
            nonlocal ts
            try:
                start_resp = self.web.chat_startStream(
                    channel=channel,
                    thread_ts=thread_ts,
                    recipient_team_id=self.team_id,
                    recipient_user_id=user_id,
                    username=self.display_name,
                )
            except SlackApiError as e:
                err = e.response.get("error")
                log.error("chat.startStream failed (%s)", err)
                audit_log(
                    f":warning: {self.display_name} `chat.startStream` rejected → `{err}`. "
                    f"Falling back to plain `chat.postMessage` (no streaming)."
                )
                return False
            got_ts = start_resp.get("ts") if start_resp is not None else None
            if not got_ts:
                ok = start_resp.get("ok") if start_resp is not None else None
                log.error("chat.startStream returned no ts: ok=%s", ok)
                audit_log(
                    f":warning: {self.display_name} `chat.startStream` returned no `ts` "
                    f"(ok=`{ok}`). Falling back to plain `chat.postMessage`."
                )
                return False
            ts = got_ts
            return True

        try:
            stream_iter = stream_reply(
                model=self.model,
                system_prompt=system_prompt,
                messages=messages,
            )
            for event_type, payload in stream_iter:
                if event_type == "error":
                    # If the subprocess errored mid-stream (after we opened
                    # the Slack placeholder), don't let the traceback splash
                    # into audit — finalize the placeholder with a
                    # "connection dropped" note and return gracefully.
                    if started_streaming:
                        log.warning("claude subprocess dropped mid-stream: %s", payload[:200])
                        self._finalize_dropped_stream(channel, ts, buf)
                        audit_log(
                            f":electric_plug: {self.display_name} CLI dropped mid-stream. "
                            f"Partial reply flushed; asked user to retry."
                        )
                        loading_stop.set()
                        self._set_status(channel, thread_ts, "")
                        return (buf or "(dropped)"), EMPTY_USAGE
                    error_text = payload
                    continue
                if event_type == "final":
                    final_text = payload
                    break
                if event_type != "delta":
                    continue

                buf += payload

                # Detection phase: scan the full buffer (not just prefix)
                # for ```blockkit. Defer the text-vs-card commit until near
                # the loading floor so a slow pre-fence sentence doesn't
                # get mis-committed to plain-text streaming.
                if detect_phase:
                    decision = _blockkit_decision(
                        buf, time.monotonic() - t_start, floor_s
                    )
                    if decision == "buffer":
                        continue
                    detect_phase = False
                    is_blockkit = decision == "blockkit"
                    if is_blockkit:
                        continue

                if is_blockkit:
                    continue

                if not started_streaming:
                    remaining = floor_s - (time.monotonic() - t_start)
                    if remaining > 0:
                        time.sleep(remaining)
                    if not _start_stream():
                        loading_stop.set()
                        self._set_status(channel, thread_ts, "")
                        for ev_type2, payload2 in stream_iter:
                            if ev_type2 == "delta":
                                buf += payload2
                            elif ev_type2 == "final":
                                final_text = payload2
                                break
                            elif ev_type2 == "error":
                                error_text = payload2
                        text = (final_text or buf).strip() or "(no response)"
                        self._post(channel, thread_ts, text)
                        return text, EMPTY_USAGE
                    started_streaming = True
                    loading_stop.set()
                    self._set_status(channel, thread_ts, "")
                elif (time.monotonic() - last_flush) * 1000 >= STREAM_FLUSH_MS:
                    _flush()
        finally:
            loading_stop.set()

        if error_text and not final_text:
            raise RuntimeError(f"claude CLI error: {error_text[:500]}")

        full_text = final_text.strip() or buf.strip() or "(no response)"

        # Late-arriving Block Kit detection: when the CLI only emits a terminal
        # `result` event (no incremental deltas), detect_phase never flipped.
        # Re-inspect the full text now.
        if detect_phase and self.blockkit_enabled:
            is_blockkit = _has_blockkit_candidate(full_text)

        # Block Kit path: parse the fence, wait out the floor, post as blocks.
        if is_blockkit:
            blocks, tier = _extract_blockkit_json(full_text)
            violations: list[str] = _validate_blocks(blocks) if blocks else []
            if violations:
                log.warning("blockkit schema violations (tier=%s): %s", tier, violations)
                blocks = None
            remaining = floor_s - (time.monotonic() - t_start)
            if remaining > 0:
                time.sleep(remaining)
            loading_stop.set()
            self._set_status(channel, thread_ts, "")
            if blocks:
                try:
                    self.web.chat_postMessage(
                        channel=channel,
                        thread_ts=thread_ts,
                        blocks=blocks,
                        text="(Block Kit card)",
                        username=self.display_name,
                    )
                    if tier != "strict":
                        log.info("blockkit recovered via tier=%s", tier)
                except SlackApiError as e:
                    err = e.response.get("error")
                    log.error("chat.postMessage (blocks) failed: %s", err)
                    audit_log(f":warning: {self.display_name} blocks post rejected → `{err}`")
                    self._post(
                        channel,
                        thread_ts,
                        "Sorry, I built the card but Slack rejected it. Try again?",
                    )
            else:
                failure_class = "schema_error" if violations else tier
                detail = (
                    f"violations={violations}"
                    if violations
                    else f"raw start: ```{full_text[:200]}```"
                )
                audit_log(
                    f":warning: {self.display_name} Block Kit fence unpostable "
                    f"(class=`{failure_class}`). {detail}"
                )
                self._post(channel, thread_ts, "Sorry, I botched the card formatting. Try again?")
            return full_text, EMPTY_USAGE

        # Short-reply case: the model finished before _blockkit_decision
        # crossed into "text" (fast, short answer; under the loading
        # floor). Open a stream now and replay the buffer so short
        # answers animate the same way long ones do. If startStream
        # can't deliver a ts, fall back to chat.postMessage.
        if not started_streaming:
            remaining = floor_s - (time.monotonic() - t_start)
            if remaining > 0:
                time.sleep(remaining)
            loading_stop.set()
            self._set_status(channel, thread_ts, "")
            if _start_stream():
                self._replay_buffered_text(channel, ts, full_text)
            else:
                self._post(channel, thread_ts, full_text)
            return full_text, EMPTY_USAGE

        # Long-reply path: stream was opened mid-generation. Replay
        # whatever's left in `buf` at the same paced cadence.
        self._replay_buffered_text(channel, ts, buf)
        return full_text, EMPTY_USAGE

    def _reply_no_stream(
        self,
        channel: str,
        thread_ts: str,
        system_prompt: str,
        messages: list[dict[str, str]],
        t_start: float,
        floor_s: float,
        loading_stop: Event,
    ) -> tuple[str, dict[str, Any]]:
        parts: list[str] = []
        for ev_type, payload in stream_reply(
            model=self.model,
            system_prompt=system_prompt,
            messages=messages,
        ):
            if ev_type == "delta":
                parts.append(payload)
            elif ev_type == "final":
                full = payload.strip()
                if full:
                    parts = [full]
                break
            elif ev_type == "error":
                raise RuntimeError(f"claude CLI error: {payload[:500]}")

        text = "".join(parts).strip() or "(no response)"

        remaining = floor_s - (time.monotonic() - t_start)
        if remaining > 0:
            time.sleep(remaining)
        loading_stop.set()
        self._set_status(channel, thread_ts, "")

        blocks = None
        tier = "no_fence"
        violations: list[str] = []
        if self.blockkit_enabled:
            blocks, tier = _extract_blockkit_json(text)
            violations = _validate_blocks(blocks) if blocks else []
            if violations:
                log.warning("blockkit schema violations (tier=%s): %s", tier, violations)
                blocks = None
        if blocks:
            try:
                self.web.chat_postMessage(
                    channel=channel,
                    thread_ts=thread_ts,
                    blocks=blocks,
                    text="(Block Kit card)",
                    username=self.display_name,
                )
            except SlackApiError:
                self._post(channel, thread_ts, text)
        else:
            self._post(channel, thread_ts, text)
        return text, EMPTY_USAGE


def main() -> int:
    parser = argparse.ArgumentParser(description="Slack AI app simulator")
    parser.add_argument(
        "--no-stream",
        action="store_true",
        help="Disable native text streaming (chat.startStream); use single chat.postMessage instead.",
    )
    parser.add_argument("--debug", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.debug else logging.INFO,
        format="%(asctime)s %(levelname)-7s %(name)s: %(message)s",
    )

    Simulator(stream=not args.no_stream).run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
